### ISSUE TITLE
castore on hex.pm doesn't have certdata task

### ISSUE THREAD

**Issue by bettio** [elixir-mint/castore#21]
castore 0.1.7 from hex.pm doesn't have certdata task and the hex package doesn't have `lib/mix/tasks/certdata.ex`.

**Comment by ericmj** [comment]
This is by design. The task is only for internal use to update the certificate data.

**Comment by whatyouhide** [comment]
Agreed, if you need to run it you could always pull the repo from GitHub. I'll close the issue but @bettio if you have a specific use case in mind that you needed this for feel free to let us know and we can try to think of a solution :) Thanks!
