### ISSUE TITLE
Prepare for DST Root CA X3 expiry

### ISSUE THREAD

**Issue by voltone** [elixir-mint/castore#31]
At 14:01:15 UTC on September 30th, the "DST Root CA X3" certificate will expire. I'm sure the certificate will then be removed upstream and CI will then notify you to publish an update. However, I'm worried that quite a few thing may have broken by that time.

I wrote up the details in [this post](https://blog.voltone.net/post/29) a couple of days ago, but TL;DR:

* In OTP 23.3 and later, an expired root CA in the trust store causes TLS handshake failures *without* invoking any `partial_chain` handler (used by many clients, including Mint and Hackney, to support cross-signed certificates)
* Let's Encrypt [is encouraging](https://community.letsencrypt.org/t/production-chain-changes/150739) the use of a cross-signed version of their own root CA, signed by the expiring "DST Root CA X3" certificate, to ensure compatibility with old Android devices

As a result, the moment "DST Root CA X3" expires clients such as Mint will fail to connect to servers with a Let's Encrypt certificate that have been configured to serve up the longer (default) chain. I believe the only way to resolve this, besides configuring the server to omit the cross-signed CA certificate, is to remove the "DST Root CA X3" certificate from the trust store.

We may have to consider releasing a version of `castore` that omits the "DST Root CA X3" certificate some time before September 30th, to give people a chance to upgrade their code and deploy it to production, to stop applications from breaking that day. I thought I'd raise the issue well ahead of time so we can explore alternatives. What do you think...?

**Comment by voltone** [comment]
See also https://github.com/erlang/otp/issues/4877

**Comment by ericmj** [comment]
Now that https://github.com/erlang/otp/issues/4877 is fixed is there something to still do on castore?

What are there downsides of removing "DST Root CA X3" from the store?

**Comment by voltone** [comment]
> Now that erlang/otp#4877 is fixed is there something to still do on castore?

I need to spend some time with 23.3.4.5 and 24.0.4. Probably not much, except encourage people to upgrade.

> What are there downsides of removing "DST Root CA X3" from the store?

It needs to be removed once it expires. The downside of removing it earlier is that there is a probability, however unlikely, that someone was still counting on CA being trusted by clients in the last few days of its validity. And removing it close to Sep 30th means very few people will have upgraded: I don't suppose many people run `mix deps.update castore` regularly (they should).

**Comment by ericmj** [comment]
We automatically remove certificates after they have expired, but end users will only get the change after we have published a new version (usually they day after) and they have updated the package.

It seems we are between rock and a hard place, if we remove the certificate early we run the risk of breaking users that rely on the certificate and if we remove it late then we will break users that haven't updated their OTP version.

The benefit of removing it early is that users will presumably run into the potential issue soon after they have updated castore and deployed their changes and can then roll back, instead of it happening at an inconvenient time and they have to figure out what is going on.

**Comment by voltone** [comment]
> The benefit of removing it early is that users will presumably run into the potential issue soon after they have updated castore and deployed their changes and can then roll back, instead of it happening at an inconvenient time and they have to figure out what is going on.

Right. Maybe an RC sometime soon, then inform the community and suggest people try it out (e.g. in a staging environment), and then make it official mid-September? The thing is, it might mess up your version numbers if there are some other upstream changes before then...

**Comment by ericmj** [comment]
> Right. Maybe an RC sometime soon, then inform the community and suggest people try it out (e.g. in a staging environment), and then make it official mid-September?

👍 

> The thing is, it might mess up your version numbers if there are some other upstream changes before then...

We can always retire the RC and publish a new one. Since `-prerelease` versions are not resolved unless you explicitly ask for them it's relatively safe.
