### ISSUE TITLE
could not read file "VERSION" with castore 1.0.2

### ISSUE THREAD

**Issue by toranb** [elixir-mint/castore#60]
```
** (File.Error) could not read file "VERSION": no such file or directory
    (elixir 1.14.4) lib/file.ex:358: File.read!/1
    /Users/toranb/code/helloworld/deps/castore/mix.exs:53: CAStore.MixProject.version/0
    /Users/toranb/code/helloworld/deps/castore/mix.exs:9: CAStore.MixProject.project/0
    (mix 1.14.4) lib/mix/project.ex:838: Mix.Project.get_project_config/1
```
    
I was installing the latest dependencies for a project this morning and found the latest castore is now missing a version file. 

Thanks again for supporting open source!

**Comment by ajdawson** [comment]
Just had the same issue. I wonder if `VERSION` needs to be added here to ensure it is part of the hex package: https://github.com/elixir-mint/castore/blob/e567f792cd898b44dbf0fbb9a02b9ba94ad4a71f/mix.exs#L45

**Comment by aiwaiwa** [comment]
Same here. It's definitely coming from non-existing "VERSION" file in `mix.exs` script.

```elixir
  defp version do
    "VERSION"
    |> File.read!()
    |> String.trim()
  end
```

**Comment by ericmj** [comment]
Thanks for opening the issue. A fixed version has been published.

**Comment by aiwaiwa** [comment]
Placing a new VERSION file inside `deps/castore` with the content of `1.0.2` seems to be a workaround while the release cycle is finished.

**Comment by oliver-kriska** [comment]
btw deploy/publish crashed https://github.com/elixir-mint/castore/actions/runs/4980968501/jobs/8914565862

**Comment by ericmj** [comment]
> btw deploy/publish crashed

It's crashing because I published on my local machine. The fixed version is live.
